### ISSUE TITLE
[error]  signalled when all packages are up-to-date ...

### ISSUE THREAD

**Issue by rprimus** [Silex/package-utils#1]
Hello,

Cheers for creating this.

I do not think that it should signal an error when all packages are up-tp-date.
An informational message can be posted,  but this should not halt the program.

(I've written a script that call emacs with **-f package-utils-upgrade-all**.)

**Comment by Silex** [comment]
Hum, yeah I think you're right.

The problem with classic `message` is that for some reason it was not displayed by me. Using `error` also made the logic simpler. I'll change it to normal `message` again soon and you can test :)

**Comment by Silex** [comment]
@rprimus: can you check https://github.com/Silex/package-utils/tree/no-error and tell me if it works for you?

Also, I'm not sure what behavior should `package-utils-upgrade-by-name` have when there's no packages to upgrade... should it `error`?

**Comment by rprimus** [comment]
`no-error` works perfectly!

@Silex `package-utils-upgrade-by-name`  should `error` if the package cannot be found (spelling mistake).  It looks like `epl-find-installed-packages` should be taking care of this at the lower level.

In using/testing `...-by-name` functions, what form does the name need to be entered as - (eg string)?

**Comment by Silex** [comment]
Currently the name has to be entered as a string, but I'm making changes so you can pass either a symbol or a string.

Please check the `master` branch in a short while.

**Comment by Silex** [comment]
@rprimus: can you give master a try? if things are ok I'll then make it `0.3.0`

**Comment by rprimus** [comment]
@Silex: Tested and all looks good!

Thank you!
