### ISSUE TITLE
support package-archive-priorities

### ISSUE THREAD

**Issue by fommil** [Silex/package-utils#4]
I recently updated my emacs config to use `package-archive-priorities`, e.g. prefer stable over melpa snapshots:

``` elisp
  (setq
   package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                      ("org" . "http://orgmode.org/elpa/")
                      ("melpa-stable" . "http://stable.melpa.org/packages/")
                      ("melpa" . "http://melpa.org/packages/"))
   package-archive-priorities '(("melpa-stable" . 1))))
```

however `package-utils-upgrade-all` ignores the priorities and will upgrade all packages to the absolute latest.

Do you think this is something your lib could support?

**Comment by Silex** [comment]
Interesting, I did not know about `package-archive-priorities`.

This package uses `epl-upgrade` from https://github.com/cask/epl to do its task...

I opened an issue there, we'll see how it goes.

**Comment by Silex** [comment]
I realised I could also drop epl entirely and do exactly what `M-x package-list-package U x` does.

Do you think it'd be better?

**Comment by fommil** [comment]
:-)

**Comment by Silex** [comment]
@fommil: can you check my PR on epl? it'd fix your issue... if it does, then it's simpler to simply have it merged there.

**Comment by Silex** [comment]
@fommil: can you test https://github.com/Silex/package-utils/tree/package-implementation ?

This should fix your issue.

**Comment by fommil** [comment]
:smile: I ran it and it didn't do anything, which I think means it's working because I already did a manual `list-packages` this morning... so it is not trying to upgrade everything to latest! Thank you so much for looking into this. I will try to upgrade over the next few days to see if it upgrades things on stable.

**Comment by Silex** [comment]
Alright, keep me informed. It does almost exactly the same thing as running `list-packages U x` so it should work.

**Comment by fommil** [comment]
ok, seems to work great!

**Comment by Silex** [comment]
Alright :+1:

**Comment by Silex** [comment]
Merged.
