### ISSUE TITLE
Upgrading `lsp-mode` with `package-utils-upgrade-all` fails every time

### ISSUE THREAD

**Issue by ideasman42** [Silex/package-utils#9]
Updating existing packages doesn't work properly in some cases, see this report for lsp-mode.

https://github.com/emacs-lsp/lsp-mode/issues/2552#issuecomment-764964290

I've written a [small package](https://gitlab.com/ideasman42/emacs-package-utils-upgrade-all-and-recompile) that resolves this by rebuilding byte-code in an external emacs instance after an update, however it would be better if something like this is handled by package-utils it's self.

**Comment by Silex** [comment]
> Given how package.el works delete + restart + install is the only way to guarantee that packages are installed properly. It is also recommended by our docs.

I'm not sure it makes sense to work around that. I mean, it seems a limitation in `package.el`, I don't think `package-utils`  should attemp to fix it.

That said if you think a PR makes sense just go ahead, I'll likely merge it :-)

Would you like to become a maintainer?

**Comment by ideasman42** [comment]
@Silex thanks for the feedback.

Before I look into making this a PR.

- Would this be an option for `package-utils-upgrade-all` or a separate function?
- Is it acceptable to launch a new instance of emacs for the byte-code compiling?
  (since this is the only way I found to reliably generate byte-code when older macros might already be loaded into memory).
- Currently I'm scanning the `user-emacs-directory` for `elc` files, it would be better to scan the elc files of all known installed packages - which I'll need to look into.

I'm fine to become a maintainer.

**Comment by Silex** [comment]
I added you as a collaborator.

I think I would keep it as `package-utils-upgrade-all-and-recompile` (separate function), maybe add some variants like `-and-restart` etc

The current API is not so amazing so feel free to propose a reorganisation that makes more sense.

Please propose your changes through PRs where you commit to a different branch than master, then we can discuss a bit and you can then merge.

**Comment by ideasman42** [comment]
Submitted PR for this issue.

All package directories are now operated on (this replaces logic that scanned `load-paths`).

**Comment by Silex** [comment]
Following in #10
